meta-virtualization: bump to revision 9fe9977
This includes the following changes:

9fe9977 ceph: add support for python3.9
6687be2 ceph: add missing include for atomic<bool>
f7687c8 xen: Fix xenpmd compilation error on arm32
17660b5 xen: Fix python libraries installation on multilib
82bca23 xvisor: fix build with gcc-10
8e4b1e3 xvisor: skip QA checks ldflags and textrel
8afc0b3 cloud-init: fix usrmerge QA error:
19c3d8b cloud-init: add dependency on systemd to fix installed-vs-shipped QA issue
515f39e guest: import cloud-init from meta-openstack
afef7f0 container-base: make CONTAINER_SHELL a conditional image install
e9a8756 containers: add a dummy provider for /bin/sh and /bin/env
74e0b8d python3-docker-compose: upgrade 1.26.0 to 1.27.4
2f83558 python3-docker: upgrade 4.2.1 to 4.3.1
af5ed18 nagios-core: uprev v4.4.3 -> v4.4.6
cc99031 xen: extend SYSROOT_DIRS to include installed binaries
3620511 xen: run do_deploy after do_compile and do_populate_sysroot
d47e714 nagios-core: use /run instead of /var/run in systemd service file
3f8f47e nagios-nsca: use /run instead of /var/run in systemd service file
28cca9a openvswitch: use /run instead of /var/run in systemd service file
9d5d904 containerd: provide 'ctr' along with 'containerd-ctr'
7a8167f xen: Fix x86_64 xen-tools installation
28fda6d kubernetes: Fix race issue for installing go2make
80d83ea containerd: fix x86-64 build
f59d55e conf: add gatesgarth to compat, drop zeus
1d86197 ipxe: Fix gcc10 compilation
ef00e94 containerd: package runc shims
68a9860 containerd: depreciate containerd-docker
d3207bb containerd: upgrade to 1.4.x

Signed-off-by: Pierre-Jean Texier <texier.pj2@gmail.com>